# admin SPA -> https://admin.ranjbar.dev
server {
    listen 80;
    listen [::]:80;
    server_name admin.ranjbar.dev;

    root /opt/hesab/admin;
    index index.html;

    location /_next/static/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri.html $uri/ /index.html;
    }
}
