// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_auth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearAdminAvatar = `-- name: ClearAdminAvatar :exec
UPDATE admins SET avatar = NULL, avatar_type = '' WHERE id = $1
`

func (q *Queries) ClearAdminAvatar(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, clearAdminAvatar, id)
	return err
}

const consumePasswordReset = `-- name: ConsumePasswordReset :exec
UPDATE admin_password_resets SET consumed_at = now() WHERE id = $1
`

func (q *Queries) ConsumePasswordReset(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, consumePasswordReset, id)
	return err
}

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO admins (first_name, last_name, email, phone_number, is_male, password_hash, totp_secret)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, first_name, last_name, email, phone_number, is_male, password_hash, totp_secret, created_at, avatar, avatar_type
`

type CreateAdminParams struct {
	FirstName    string `json:"first_name"`
	LastName     string `json:"last_name"`
	Email        string `json:"email"`
	PhoneNumber  string `json:"phone_number"`
	IsMale       bool   `json:"is_male"`
	PasswordHash string `json:"password_hash"`
	TotpSecret   string `json:"totp_secret"`
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (Admin, error) {
	row := q.db.QueryRow(ctx, createAdmin,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.PhoneNumber,
		arg.IsMale,
		arg.PasswordHash,
		arg.TotpSecret,
	)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PhoneNumber,
		&i.IsMale,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.CreatedAt,
		&i.Avatar,
		&i.AvatarType,
	)
	return i, err
}

const getAdminAvatar = `-- name: GetAdminAvatar :one
SELECT avatar, avatar_type FROM admins WHERE id = $1
`

type GetAdminAvatarRow struct {
	Avatar     []byte `json:"avatar"`
	AvatarType string `json:"avatar_type"`
}

func (q *Queries) GetAdminAvatar(ctx context.Context, id int64) (GetAdminAvatarRow, error) {
	row := q.db.QueryRow(ctx, getAdminAvatar, id)
	var i GetAdminAvatarRow
	err := row.Scan(&i.Avatar, &i.AvatarType)
	return i, err
}

const getAdminByID = `-- name: GetAdminByID :one
SELECT id, first_name, last_name, email, phone_number, is_male, password_hash, totp_secret, created_at, avatar, avatar_type FROM admins WHERE id = $1
`

func (q *Queries) GetAdminByID(ctx context.Context, id int64) (Admin, error) {
	row := q.db.QueryRow(ctx, getAdminByID, id)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PhoneNumber,
		&i.IsMale,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.CreatedAt,
		&i.Avatar,
		&i.AvatarType,
	)
	return i, err
}

const getAdminByPhone = `-- name: GetAdminByPhone :one
SELECT id, first_name, last_name, email, phone_number, is_male, password_hash, totp_secret, created_at, avatar, avatar_type FROM admins WHERE phone_number = $1
`

func (q *Queries) GetAdminByPhone(ctx context.Context, phoneNumber string) (Admin, error) {
	row := q.db.QueryRow(ctx, getAdminByPhone, phoneNumber)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PhoneNumber,
		&i.IsMale,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.CreatedAt,
		&i.Avatar,
		&i.AvatarType,
	)
	return i, err
}

const getLatestPasswordReset = `-- name: GetLatestPasswordReset :one
SELECT id, admin_id, code_hash, expires_at, consumed_at, created_at FROM admin_password_resets WHERE admin_id = $1 AND consumed_at IS NULL AND expires_at > now() ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLatestPasswordReset(ctx context.Context, adminID int64) (AdminPasswordReset, error) {
	row := q.db.QueryRow(ctx, getLatestPasswordReset, adminID)
	var i AdminPasswordReset
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, admin_id, token_hash, expires_at, revoked_at, created_at FROM admin_refresh_tokens WHERE token_hash = $1
`

func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash string) (AdminRefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, tokenHash)
	var i AdminRefreshToken
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertPasswordReset = `-- name: InsertPasswordReset :one
INSERT INTO admin_password_resets (admin_id, code_hash, expires_at) VALUES ($1, $2, $3) RETURNING id, admin_id, code_hash, expires_at, consumed_at, created_at
`

type InsertPasswordResetParams struct {
	AdminID   int64              `json:"admin_id"`
	CodeHash  string             `json:"code_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertPasswordReset(ctx context.Context, arg InsertPasswordResetParams) (AdminPasswordReset, error) {
	row := q.db.QueryRow(ctx, insertPasswordReset, arg.AdminID, arg.CodeHash, arg.ExpiresAt)
	var i AdminPasswordReset
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertRefreshToken = `-- name: InsertRefreshToken :one
INSERT INTO admin_refresh_tokens (admin_id, token_hash, expires_at) VALUES ($1, $2, $3) RETURNING id, admin_id, token_hash, expires_at, revoked_at, created_at
`

type InsertRefreshTokenParams struct {
	AdminID   int64              `json:"admin_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (AdminRefreshToken, error) {
	row := q.db.QueryRow(ctx, insertRefreshToken, arg.AdminID, arg.TokenHash, arg.ExpiresAt)
	var i AdminRefreshToken
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const invalidateAdminPasswordResets = `-- name: InvalidateAdminPasswordResets :exec
UPDATE admin_password_resets SET consumed_at = now() WHERE admin_id = $1 AND consumed_at IS NULL
`

func (q *Queries) InvalidateAdminPasswordResets(ctx context.Context, adminID int64) error {
	_, err := q.db.Exec(ctx, invalidateAdminPasswordResets, adminID)
	return err
}

const revokeAllAdminRefreshTokens = `-- name: RevokeAllAdminRefreshTokens :exec
UPDATE admin_refresh_tokens SET revoked_at = now() WHERE admin_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllAdminRefreshTokens(ctx context.Context, adminID int64) error {
	_, err := q.db.Exec(ctx, revokeAllAdminRefreshTokens, adminID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE admin_refresh_tokens SET revoked_at = now() WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, tokenHash)
	return err
}

const setAdminAvatar = `-- name: SetAdminAvatar :exec
UPDATE admins SET avatar = $2, avatar_type = $3 WHERE id = $1
`

type SetAdminAvatarParams struct {
	ID         int64  `json:"id"`
	Avatar     []byte `json:"avatar"`
	AvatarType string `json:"avatar_type"`
}

func (q *Queries) SetAdminAvatar(ctx context.Context, arg SetAdminAvatarParams) error {
	_, err := q.db.Exec(ctx, setAdminAvatar, arg.ID, arg.Avatar, arg.AvatarType)
	return err
}

const setAdminTOTPSecret = `-- name: SetAdminTOTPSecret :exec
UPDATE admins SET totp_secret = $2 WHERE id = $1
`

type SetAdminTOTPSecretParams struct {
	ID         int64  `json:"id"`
	TotpSecret string `json:"totp_secret"`
}

func (q *Queries) SetAdminTOTPSecret(ctx context.Context, arg SetAdminTOTPSecretParams) error {
	_, err := q.db.Exec(ctx, setAdminTOTPSecret, arg.ID, arg.TotpSecret)
	return err
}

const updateAdminPassword = `-- name: UpdateAdminPassword :exec
UPDATE admins SET password_hash = $2 WHERE id = $1
`

type UpdateAdminPasswordParams struct {
	ID           int64  `json:"id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpdateAdminPassword(ctx context.Context, arg UpdateAdminPasswordParams) error {
	_, err := q.db.Exec(ctx, updateAdminPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateAdminProfile = `-- name: UpdateAdminProfile :one
UPDATE admins SET first_name = $2, last_name = $3, email = $4, phone_number = $5, is_male = $6
WHERE id = $1 RETURNING id, first_name, last_name, email, phone_number, is_male, password_hash, totp_secret, created_at, avatar, avatar_type
`

type UpdateAdminProfileParams struct {
	ID          int64  `json:"id"`
	FirstName   string `json:"first_name"`
	LastName    string `json:"last_name"`
	Email       string `json:"email"`
	PhoneNumber string `json:"phone_number"`
	IsMale      bool   `json:"is_male"`
}

func (q *Queries) UpdateAdminProfile(ctx context.Context, arg UpdateAdminProfileParams) (Admin, error) {
	row := q.db.QueryRow(ctx, updateAdminProfile,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.PhoneNumber,
		arg.IsMale,
	)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PhoneNumber,
		&i.IsMale,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.CreatedAt,
		&i.Avatar,
		&i.AvatarType,
	)
	return i, err
}
