// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: businesses_admin.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminCountBusinesses = `-- name: AdminCountBusinesses :one
SELECT count(*) FROM businesses b WHERE b.deleted_at IS NULL AND ($1::text IS NULL OR b.name ILIKE '%' || $1 || '%')
`

func (q *Queries) AdminCountBusinesses(ctx context.Context, name pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountBusinesses, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminGetBusiness = `-- name: AdminGetBusiness :one
SELECT b.id, b.name, b.owner_user_id, b.created_at, b.deleted_at, u.first_name AS owner_first_name, u.last_name AS owner_last_name, u.phone_number AS owner_phone_number FROM businesses b JOIN users u ON u.id = b.owner_user_id WHERE b.id = $1 AND b.deleted_at IS NULL
`

type AdminGetBusinessRow struct {
	ID               int64              `json:"id"`
	Name             string             `json:"name"`
	OwnerUserID      int64              `json:"owner_user_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	OwnerFirstName   string             `json:"owner_first_name"`
	OwnerLastName    string             `json:"owner_last_name"`
	OwnerPhoneNumber string             `json:"owner_phone_number"`
}

func (q *Queries) AdminGetBusiness(ctx context.Context, id int64) (AdminGetBusinessRow, error) {
	row := q.db.QueryRow(ctx, adminGetBusiness, id)
	var i AdminGetBusinessRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.OwnerFirstName,
		&i.OwnerLastName,
		&i.OwnerPhoneNumber,
	)
	return i, err
}

const adminListBusinesses = `-- name: AdminListBusinesses :many
SELECT b.id, b.name, b.owner_user_id, b.created_at, b.deleted_at, u.first_name AS owner_first_name, u.last_name AS owner_last_name, u.phone_number AS owner_phone_number, (SELECT count(*) FROM business_members WHERE business_id = b.id)::bigint AS member_count FROM businesses b JOIN users u ON u.id = b.owner_user_id WHERE b.deleted_at IS NULL AND ($1::text IS NULL OR b.name ILIKE '%' || $1 || '%') ORDER BY b.created_at DESC LIMIT $3 OFFSET $2
`

type AdminListBusinessesParams struct {
	Name pgtype.Text `json:"name"`
	Off  int32       `json:"off"`
	Lim  int32       `json:"lim"`
}

type AdminListBusinessesRow struct {
	ID               int64              `json:"id"`
	Name             string             `json:"name"`
	OwnerUserID      int64              `json:"owner_user_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	OwnerFirstName   string             `json:"owner_first_name"`
	OwnerLastName    string             `json:"owner_last_name"`
	OwnerPhoneNumber string             `json:"owner_phone_number"`
	MemberCount      int64              `json:"member_count"`
}

func (q *Queries) AdminListBusinesses(ctx context.Context, arg AdminListBusinessesParams) ([]AdminListBusinessesRow, error) {
	rows, err := q.db.Query(ctx, adminListBusinesses, arg.Name, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListBusinessesRow
	for rows.Next() {
		var i AdminListBusinessesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerUserID,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.OwnerFirstName,
			&i.OwnerLastName,
			&i.OwnerPhoneNumber,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListJoinedBusinesses = `-- name: AdminListJoinedBusinesses :many
SELECT b.id, b.name, m.role, trim(concat_ws(' ', u.first_name, u.last_name)) AS owner_name, b.created_at FROM businesses b JOIN business_members m ON m.business_id = b.id AND m.user_id = $1 JOIN users u ON u.id = b.owner_user_id WHERE m.role <> 'owner' AND b.deleted_at IS NULL ORDER BY b.created_at DESC
`

type AdminListJoinedBusinessesRow struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Role      string             `json:"role"`
	OwnerName string             `json:"owner_name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) AdminListJoinedBusinesses(ctx context.Context, userID int64) ([]AdminListJoinedBusinessesRow, error) {
	rows, err := q.db.Query(ctx, adminListJoinedBusinesses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListJoinedBusinessesRow
	for rows.Next() {
		var i AdminListJoinedBusinessesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.OwnerName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListOwnedBusinesses = `-- name: AdminListOwnedBusinesses :many
SELECT b.id, b.name, b.created_at, (SELECT count(*) FROM business_members WHERE business_id = b.id)::bigint AS member_count FROM businesses b WHERE b.owner_user_id = $1 AND b.deleted_at IS NULL ORDER BY b.created_at DESC
`

type AdminListOwnedBusinessesRow struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	MemberCount int64              `json:"member_count"`
}

func (q *Queries) AdminListOwnedBusinesses(ctx context.Context, ownerUserID int64) ([]AdminListOwnedBusinessesRow, error) {
	rows, err := q.db.Query(ctx, adminListOwnedBusinesses, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListOwnedBusinessesRow
	for rows.Next() {
		var i AdminListOwnedBusinessesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
