// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: businesses.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMember = `-- name: AddMember :one
INSERT INTO business_members (business_id, user_id, role) VALUES ($1, $2, $3) RETURNING id, business_id, user_id, role, created_at
`

type AddMemberParams struct {
	BusinessID int64  `json:"business_id"`
	UserID     int64  `json:"user_id"`
	Role       string `json:"role"`
}

func (q *Queries) AddMember(ctx context.Context, arg AddMemberParams) (BusinessMember, error) {
	row := q.db.QueryRow(ctx, addMember, arg.BusinessID, arg.UserID, arg.Role)
	var i BusinessMember
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const createBusiness = `-- name: CreateBusiness :one
INSERT INTO businesses (name, owner_user_id) VALUES ($1, $2) RETURNING id, name, owner_user_id, created_at, deleted_at
`

type CreateBusinessParams struct {
	Name        string `json:"name"`
	OwnerUserID int64  `json:"owner_user_id"`
}

func (q *Queries) CreateBusiness(ctx context.Context, arg CreateBusinessParams) (Business, error) {
	row := q.db.QueryRow(ctx, createBusiness, arg.Name, arg.OwnerUserID)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createInvite = `-- name: CreateInvite :one
INSERT INTO business_invites (business_id, user_id, role, invited_by) VALUES ($1, $2, $3, $4) RETURNING id, business_id, user_id, role, invited_by, status, created_at, responded_at
`

type CreateInviteParams struct {
	BusinessID int64       `json:"business_id"`
	UserID     int64       `json:"user_id"`
	Role       string      `json:"role"`
	InvitedBy  pgtype.Int8 `json:"invited_by"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (BusinessInvite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.BusinessID,
		arg.UserID,
		arg.Role,
		arg.InvitedBy,
	)
	var i BusinessInvite
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.Status,
		&i.CreatedAt,
		&i.RespondedAt,
	)
	return i, err
}

const getActiveUserByPhone = `-- name: GetActiveUserByPhone :one
SELECT id, first_name, last_name, email, phone_number, password_hash, totp_secret, created_at, national_id, account_type, status, deleted_at FROM users WHERE phone_number = $1 AND deleted_at IS NULL
`

func (q *Queries) GetActiveUserByPhone(ctx context.Context, phoneNumber string) (User, error) {
	row := q.db.QueryRow(ctx, getActiveUserByPhone, phoneNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.CreatedAt,
		&i.NationalID,
		&i.AccountType,
		&i.Status,
		&i.DeletedAt,
	)
	return i, err
}

const getBusiness = `-- name: GetBusiness :one
SELECT id, name, owner_user_id, created_at, deleted_at FROM businesses WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetBusiness(ctx context.Context, id int64) (Business, error) {
	row := q.db.QueryRow(ctx, getBusiness, id)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getInvite = `-- name: GetInvite :one
SELECT id, business_id, user_id, role, invited_by, status, created_at, responded_at FROM business_invites WHERE id = $1
`

func (q *Queries) GetInvite(ctx context.Context, id int64) (BusinessInvite, error) {
	row := q.db.QueryRow(ctx, getInvite, id)
	var i BusinessInvite
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.Status,
		&i.CreatedAt,
		&i.RespondedAt,
	)
	return i, err
}

const getMemberRole = `-- name: GetMemberRole :one
SELECT role FROM business_members WHERE business_id = $1 AND user_id = $2
`

type GetMemberRoleParams struct {
	BusinessID int64 `json:"business_id"`
	UserID     int64 `json:"user_id"`
}

func (q *Queries) GetMemberRole(ctx context.Context, arg GetMemberRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getMemberRole, arg.BusinessID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const listMembers = `-- name: ListMembers :many
SELECT m.user_id, m.role, u.first_name, u.last_name, u.phone_number, m.created_at FROM business_members m JOIN users u ON u.id = m.user_id WHERE m.business_id = $1 ORDER BY m.created_at
`

type ListMembersRow struct {
	UserID      int64              `json:"user_id"`
	Role        string             `json:"role"`
	FirstName   string             `json:"first_name"`
	LastName    string             `json:"last_name"`
	PhoneNumber string             `json:"phone_number"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListMembers(ctx context.Context, businessID int64) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersRow
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Role,
			&i.FirstName,
			&i.LastName,
			&i.PhoneNumber,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingInvitesForBusiness = `-- name: ListPendingInvitesForBusiness :many
SELECT i.id, i.business_id, i.user_id, u.first_name, u.last_name, u.phone_number, i.role, i.created_at FROM business_invites i JOIN users u ON u.id = i.user_id JOIN businesses b ON b.id = i.business_id WHERE i.business_id = $1 AND i.status = 'pending' AND b.deleted_at IS NULL ORDER BY i.created_at
`

type ListPendingInvitesForBusinessRow struct {
	ID          int64              `json:"id"`
	BusinessID  int64              `json:"business_id"`
	UserID      int64              `json:"user_id"`
	FirstName   string             `json:"first_name"`
	LastName    string             `json:"last_name"`
	PhoneNumber string             `json:"phone_number"`
	Role        string             `json:"role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListPendingInvitesForBusiness(ctx context.Context, businessID int64) ([]ListPendingInvitesForBusinessRow, error) {
	rows, err := q.db.Query(ctx, listPendingInvitesForBusiness, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingInvitesForBusinessRow
	for rows.Next() {
		var i ListPendingInvitesForBusinessRow
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.UserID,
			&i.FirstName,
			&i.LastName,
			&i.PhoneNumber,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingInvitesForUser = `-- name: ListPendingInvitesForUser :many
SELECT i.id, i.business_id, b.name AS business_name, i.role, i.status, COALESCE(NULLIF(trim(concat_ws(' ', u.first_name, u.last_name)), ''), '') AS invited_by_name, i.created_at FROM business_invites i JOIN businesses b ON b.id = i.business_id LEFT JOIN users u ON u.id = i.invited_by WHERE i.user_id = $1 AND i.status = 'pending' AND b.deleted_at IS NULL ORDER BY i.created_at
`

type ListPendingInvitesForUserRow struct {
	ID            int64              `json:"id"`
	BusinessID    int64              `json:"business_id"`
	BusinessName  string             `json:"business_name"`
	Role          string             `json:"role"`
	Status        string             `json:"status"`
	InvitedByName interface{}        `json:"invited_by_name"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListPendingInvitesForUser(ctx context.Context, userID int64) ([]ListPendingInvitesForUserRow, error) {
	rows, err := q.db.Query(ctx, listPendingInvitesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingInvitesForUserRow
	for rows.Next() {
		var i ListPendingInvitesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.BusinessName,
			&i.Role,
			&i.Status,
			&i.InvitedByName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserBusinesses = `-- name: ListUserBusinesses :many
SELECT b.id, b.name, b.owner_user_id, b.created_at, m.role FROM businesses b JOIN business_members m ON m.business_id = b.id AND m.user_id = $1 WHERE b.deleted_at IS NULL ORDER BY b.created_at
`

type ListUserBusinessesRow struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	OwnerUserID int64              `json:"owner_user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Role        string             `json:"role"`
}

func (q *Queries) ListUserBusinesses(ctx context.Context, userID int64) ([]ListUserBusinessesRow, error) {
	rows, err := q.db.Query(ctx, listUserBusinesses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserBusinessesRow
	for rows.Next() {
		var i ListUserBusinessesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerUserID,
			&i.CreatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMember = `-- name: RemoveMember :exec
DELETE FROM business_members WHERE business_id = $1 AND user_id = $2
`

type RemoveMemberParams struct {
	BusinessID int64 `json:"business_id"`
	UserID     int64 `json:"user_id"`
}

func (q *Queries) RemoveMember(ctx context.Context, arg RemoveMemberParams) error {
	_, err := q.db.Exec(ctx, removeMember, arg.BusinessID, arg.UserID)
	return err
}

const renameBusiness = `-- name: RenameBusiness :one
UPDATE businesses SET name = $2 WHERE id = $1 AND deleted_at IS NULL RETURNING id, name, owner_user_id, created_at, deleted_at
`

type RenameBusinessParams struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) RenameBusiness(ctx context.Context, arg RenameBusinessParams) (Business, error) {
	row := q.db.QueryRow(ctx, renameBusiness, arg.ID, arg.Name)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const setInviteStatus = `-- name: SetInviteStatus :exec
UPDATE business_invites SET status = $2, responded_at = now() WHERE id = $1
`

type SetInviteStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) SetInviteStatus(ctx context.Context, arg SetInviteStatusParams) error {
	_, err := q.db.Exec(ctx, setInviteStatus, arg.ID, arg.Status)
	return err
}

const softDeleteBusiness = `-- name: SoftDeleteBusiness :exec
UPDATE businesses SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteBusiness(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteBusiness, id)
	return err
}

const updateMemberRole = `-- name: UpdateMemberRole :one
UPDATE business_members SET role = $3 WHERE business_id = $1 AND user_id = $2 RETURNING id, business_id, user_id, role, created_at
`

type UpdateMemberRoleParams struct {
	BusinessID int64  `json:"business_id"`
	UserID     int64  `json:"user_id"`
	Role       string `json:"role"`
}

func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) (BusinessMember, error) {
	row := q.db.QueryRow(ctx, updateMemberRole, arg.BusinessID, arg.UserID, arg.Role)
	var i BusinessMember
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}
