// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: client_auth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeUserPasswordReset = `-- name: ConsumeUserPasswordReset :exec
UPDATE user_password_resets SET consumed_at = now() WHERE id = $1
`

func (q *Queries) ConsumeUserPasswordReset(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, consumeUserPasswordReset, id)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (first_name, last_name, email, phone_number, password_hash, totp_secret)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, first_name, last_name, email, phone_number, password_hash, totp_secret, created_at
`

type CreateUserParams struct {
	FirstName    string `json:"first_name"`
	LastName     string `json:"last_name"`
	Email        string `json:"email"`
	PhoneNumber  string `json:"phone_number"`
	PasswordHash string `json:"password_hash"`
	TotpSecret   string `json:"totp_secret"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.PhoneNumber,
		arg.PasswordHash,
		arg.TotpSecret,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestUserPasswordReset = `-- name: GetLatestUserPasswordReset :one
SELECT id, user_id, code_hash, expires_at, consumed_at, created_at FROM user_password_resets WHERE user_id = $1 AND consumed_at IS NULL AND expires_at > now() ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLatestUserPasswordReset(ctx context.Context, userID int64) (UserPasswordReset, error) {
	row := q.db.QueryRow(ctx, getLatestUserPasswordReset, userID)
	var i UserPasswordReset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, first_name, last_name, email, phone_number, password_hash, totp_secret, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, first_name, last_name, email, phone_number, password_hash, totp_secret, created_at FROM users WHERE phone_number = $1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phoneNumber string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phoneNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.CreatedAt,
	)
	return i, err
}

const getUserRefreshToken = `-- name: GetUserRefreshToken :one
SELECT id, user_id, token_hash, expires_at, revoked_at, created_at FROM user_refresh_tokens WHERE token_hash = $1
`

func (q *Queries) GetUserRefreshToken(ctx context.Context, tokenHash string) (UserRefreshToken, error) {
	row := q.db.QueryRow(ctx, getUserRefreshToken, tokenHash)
	var i UserRefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertUserPasswordReset = `-- name: InsertUserPasswordReset :one
INSERT INTO user_password_resets (user_id, code_hash, expires_at) VALUES ($1, $2, $3) RETURNING id, user_id, code_hash, expires_at, consumed_at, created_at
`

type InsertUserPasswordResetParams struct {
	UserID    int64              `json:"user_id"`
	CodeHash  string             `json:"code_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertUserPasswordReset(ctx context.Context, arg InsertUserPasswordResetParams) (UserPasswordReset, error) {
	row := q.db.QueryRow(ctx, insertUserPasswordReset, arg.UserID, arg.CodeHash, arg.ExpiresAt)
	var i UserPasswordReset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertUserRefreshToken = `-- name: InsertUserRefreshToken :one
INSERT INTO user_refresh_tokens (user_id, token_hash, expires_at) VALUES ($1, $2, $3) RETURNING id, user_id, token_hash, expires_at, revoked_at, created_at
`

type InsertUserRefreshTokenParams struct {
	UserID    int64              `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertUserRefreshToken(ctx context.Context, arg InsertUserRefreshTokenParams) (UserRefreshToken, error) {
	row := q.db.QueryRow(ctx, insertUserRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i UserRefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const invalidateUserPasswordResets = `-- name: InvalidateUserPasswordResets :exec
UPDATE user_password_resets SET consumed_at = now() WHERE user_id = $1 AND consumed_at IS NULL
`

func (q *Queries) InvalidateUserPasswordResets(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, invalidateUserPasswordResets, userID)
	return err
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :exec
UPDATE user_refresh_tokens SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, revokeAllUserRefreshTokens, userID)
	return err
}

const revokeUserRefreshToken = `-- name: RevokeUserRefreshToken :exec
UPDATE user_refresh_tokens SET revoked_at = now() WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeUserRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeUserRefreshToken, tokenHash)
	return err
}

const setUserTOTPSecret = `-- name: SetUserTOTPSecret :exec
UPDATE users SET totp_secret = $2 WHERE id = $1
`

type SetUserTOTPSecretParams struct {
	ID         int64  `json:"id"`
	TotpSecret string `json:"totp_secret"`
}

func (q *Queries) SetUserTOTPSecret(ctx context.Context, arg SetUserTOTPSecretParams) error {
	_, err := q.db.Exec(ctx, setUserTOTPSecret, arg.ID, arg.TotpSecret)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           int64  `json:"id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}
