// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	ConsumePasswordReset(ctx context.Context, id int64) error
	CreateAdmin(ctx context.Context, arg CreateAdminParams) (Admin, error)
	GetAdminByID(ctx context.Context, id int64) (Admin, error)
	GetAdminByPhone(ctx context.Context, phoneNumber string) (Admin, error)
	GetLatestPasswordReset(ctx context.Context, adminID int64) (AdminPasswordReset, error)
	GetRefreshToken(ctx context.Context, tokenHash string) (AdminRefreshToken, error)
	InsertPasswordReset(ctx context.Context, arg InsertPasswordResetParams) (AdminPasswordReset, error)
	InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (AdminRefreshToken, error)
	InvalidateAdminPasswordResets(ctx context.Context, adminID int64) error
	RevokeAllAdminRefreshTokens(ctx context.Context, adminID int64) error
	RevokeRefreshToken(ctx context.Context, tokenHash string) error
	SetAdminTOTPSecret(ctx context.Context, arg SetAdminTOTPSecretParams) error
	UpdateAdminPassword(ctx context.Context, arg UpdateAdminPasswordParams) error
}

var _ Querier = (*Queries)(nil)
