// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	AdminCountUsers(ctx context.Context, arg AdminCountUsersParams) (int64, error)
	AdminCreateUser(ctx context.Context, arg AdminCreateUserParams) (User, error)
	AdminGetUser(ctx context.Context, id int64) (User, error)
	AdminListUsers(ctx context.Context, arg AdminListUsersParams) ([]User, error)
	AdminSetUserPassword(ctx context.Context, arg AdminSetUserPasswordParams) error
	AdminSetUserStatus(ctx context.Context, arg AdminSetUserStatusParams) (User, error)
	AdminSoftDeleteUser(ctx context.Context, id int64) error
	AdminUpdateUserProfile(ctx context.Context, arg AdminUpdateUserProfileParams) (User, error)
	ConsumePasswordReset(ctx context.Context, id int64) error
	ConsumeUserPasswordReset(ctx context.Context, id int64) error
	CreateAdmin(ctx context.Context, arg CreateAdminParams) (Admin, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetAdminByID(ctx context.Context, id int64) (Admin, error)
	GetAdminByPhone(ctx context.Context, phoneNumber string) (Admin, error)
	GetLatestPasswordReset(ctx context.Context, adminID int64) (AdminPasswordReset, error)
	GetLatestUserPasswordReset(ctx context.Context, userID int64) (UserPasswordReset, error)
	GetRefreshToken(ctx context.Context, tokenHash string) (AdminRefreshToken, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByPhone(ctx context.Context, phoneNumber string) (User, error)
	GetUserRefreshToken(ctx context.Context, tokenHash string) (UserRefreshToken, error)
	InsertPasswordReset(ctx context.Context, arg InsertPasswordResetParams) (AdminPasswordReset, error)
	InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (AdminRefreshToken, error)
	InsertUserPasswordReset(ctx context.Context, arg InsertUserPasswordResetParams) (UserPasswordReset, error)
	InsertUserRefreshToken(ctx context.Context, arg InsertUserRefreshTokenParams) (UserRefreshToken, error)
	InvalidateAdminPasswordResets(ctx context.Context, adminID int64) error
	InvalidateUserPasswordResets(ctx context.Context, userID int64) error
	RevokeAllAdminRefreshTokens(ctx context.Context, adminID int64) error
	RevokeAllUserRefreshTokens(ctx context.Context, userID int64) error
	RevokeRefreshToken(ctx context.Context, tokenHash string) error
	RevokeUserRefreshToken(ctx context.Context, tokenHash string) error
	SetAdminTOTPSecret(ctx context.Context, arg SetAdminTOTPSecretParams) error
	SetUserTOTPSecret(ctx context.Context, arg SetUserTOTPSecretParams) error
	UpdateAdminPassword(ctx context.Context, arg UpdateAdminPasswordParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
