// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users_admin.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminCountUsers = `-- name: AdminCountUsers :one
SELECT count(*) FROM users
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR first_name ILIKE '%' || $1 || '%')
  AND ($2::text IS NULL OR last_name ILIKE '%' || $2 || '%')
  AND ($3::text IS NULL OR phone_number ILIKE '%' || $3 || '%')
  AND ($4::text IS NULL OR status = $4)
  AND ($5::timestamptz IS NULL OR created_at >= $5)
  AND ($6::timestamptz IS NULL OR created_at < $6)
`

type AdminCountUsersParams struct {
	FirstName   pgtype.Text        `json:"first_name"`
	LastName    pgtype.Text        `json:"last_name"`
	Phone       pgtype.Text        `json:"phone"`
	Status      pgtype.Text        `json:"status"`
	CreatedFrom pgtype.Timestamptz `json:"created_from"`
	CreatedTo   pgtype.Timestamptz `json:"created_to"`
}

func (q *Queries) AdminCountUsers(ctx context.Context, arg AdminCountUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountUsers,
		arg.FirstName,
		arg.LastName,
		arg.Phone,
		arg.Status,
		arg.CreatedFrom,
		arg.CreatedTo,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminCreateUser = `-- name: AdminCreateUser :one
INSERT INTO users (first_name, last_name, email, phone_number, national_id, account_type, password_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, first_name, last_name, email, phone_number, password_hash, totp_secret, created_at, national_id, account_type, status, deleted_at
`

type AdminCreateUserParams struct {
	FirstName    string      `json:"first_name"`
	LastName     string      `json:"last_name"`
	Email        string      `json:"email"`
	PhoneNumber  string      `json:"phone_number"`
	NationalID   pgtype.Text `json:"national_id"`
	AccountType  string      `json:"account_type"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) AdminCreateUser(ctx context.Context, arg AdminCreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, adminCreateUser,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.PhoneNumber,
		arg.NationalID,
		arg.AccountType,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.CreatedAt,
		&i.NationalID,
		&i.AccountType,
		&i.Status,
		&i.DeletedAt,
	)
	return i, err
}

const adminGetUser = `-- name: AdminGetUser :one
SELECT id, first_name, last_name, email, phone_number, password_hash, totp_secret, created_at, national_id, account_type, status, deleted_at FROM users WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) AdminGetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, adminGetUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.CreatedAt,
		&i.NationalID,
		&i.AccountType,
		&i.Status,
		&i.DeletedAt,
	)
	return i, err
}

const adminListUsers = `-- name: AdminListUsers :many
SELECT id, first_name, last_name, email, phone_number, password_hash, totp_secret, created_at, national_id, account_type, status, deleted_at FROM users
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR first_name ILIKE '%' || $1 || '%')
  AND ($2::text IS NULL OR last_name ILIKE '%' || $2 || '%')
  AND ($3::text IS NULL OR phone_number ILIKE '%' || $3 || '%')
  AND ($4::text IS NULL OR status = $4)
  AND ($5::timestamptz IS NULL OR created_at >= $5)
  AND ($6::timestamptz IS NULL OR created_at < $6)
ORDER BY created_at DESC
LIMIT $8 OFFSET $7
`

type AdminListUsersParams struct {
	FirstName   pgtype.Text        `json:"first_name"`
	LastName    pgtype.Text        `json:"last_name"`
	Phone       pgtype.Text        `json:"phone"`
	Status      pgtype.Text        `json:"status"`
	CreatedFrom pgtype.Timestamptz `json:"created_from"`
	CreatedTo   pgtype.Timestamptz `json:"created_to"`
	Off         int32              `json:"off"`
	Lim         int32              `json:"lim"`
}

func (q *Queries) AdminListUsers(ctx context.Context, arg AdminListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, adminListUsers,
		arg.FirstName,
		arg.LastName,
		arg.Phone,
		arg.Status,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.PhoneNumber,
			&i.PasswordHash,
			&i.TotpSecret,
			&i.CreatedAt,
			&i.NationalID,
			&i.AccountType,
			&i.Status,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminSetUserPassword = `-- name: AdminSetUserPassword :exec
UPDATE users SET password_hash = $2 WHERE id = $1 AND deleted_at IS NULL
`

type AdminSetUserPasswordParams struct {
	ID           int64  `json:"id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) AdminSetUserPassword(ctx context.Context, arg AdminSetUserPasswordParams) error {
	_, err := q.db.Exec(ctx, adminSetUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const adminSetUserStatus = `-- name: AdminSetUserStatus :one
UPDATE users SET status = $2 WHERE id = $1 AND deleted_at IS NULL RETURNING id, first_name, last_name, email, phone_number, password_hash, totp_secret, created_at, national_id, account_type, status, deleted_at
`

type AdminSetUserStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) AdminSetUserStatus(ctx context.Context, arg AdminSetUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, adminSetUserStatus, arg.ID, arg.Status)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.CreatedAt,
		&i.NationalID,
		&i.AccountType,
		&i.Status,
		&i.DeletedAt,
	)
	return i, err
}

const adminSoftDeleteUser = `-- name: AdminSoftDeleteUser :exec
UPDATE users SET deleted_at = now(), status = 'disabled' WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) AdminSoftDeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, adminSoftDeleteUser, id)
	return err
}

const adminUpdateUserProfile = `-- name: AdminUpdateUserProfile :one
UPDATE users SET first_name = $2, last_name = $3, email = $4, national_id = $5, account_type = $6
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, first_name, last_name, email, phone_number, password_hash, totp_secret, created_at, national_id, account_type, status, deleted_at
`

type AdminUpdateUserProfileParams struct {
	ID          int64       `json:"id"`
	FirstName   string      `json:"first_name"`
	LastName    string      `json:"last_name"`
	Email       string      `json:"email"`
	NationalID  pgtype.Text `json:"national_id"`
	AccountType string      `json:"account_type"`
}

func (q *Queries) AdminUpdateUserProfile(ctx context.Context, arg AdminUpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, adminUpdateUserProfile,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.NationalID,
		arg.AccountType,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.CreatedAt,
		&i.NationalID,
		&i.AccountType,
		&i.Status,
		&i.DeletedAt,
	)
	return i, err
}
