"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import Select from "@/components/Select";
import { useBusiness } from "../Shell";
import { canManage, changeMemberRole, inviteMember, listMembers, listOutgoingInvites, removeMember, roleLabels, type Member, type OutgoingInvite, type Role, cancelInvite } from "@/lib/businesses";
import { useRequireAuth } from "@/lib/useRequireAuth";
const input = "h-10 rounded-lg border border-brand-border bg-brand-bg px-3";
const roles: [Exclude<Role, "owner">, string][] = [["admin", "مدیر"], ["accountant", "حسابدار"], ["viewer", "ناظر"]];
export default function Members() {
  const router = useRouter(); const { business, role } = useBusiness(); const { user } = useRequireAuth();
  const [members, setMembers] = useState<Member[]>([]); const [invites, setInvites] = useState<OutgoingInvite[]>([]); const [phone, setPhone] = useState(""); const [inviteRole, setInviteRole] = useState<Exclude<Role, "owner">>("viewer");
  const roleOptions = roles.map(([value, label]) => ({ value, label }));
  const load = async () => { try { const result = await listMembers(business.id); setMembers(result.members); if (canManage(role)) setInvites((await listOutgoingInvites(business.id)).invites); } catch (error) { toast.error(error instanceof Error ? error.message : "خطا"); } };
  useEffect(() => { void load(); }, [business.id, role]);
  async function invite(event: React.FormEvent) { event.preventDefault(); try { await inviteMember(business.id, { phone_number: phone, role: inviteRole }); setPhone(""); toast.success("دعوت ارسال شد"); void load(); } catch (error) { toast.error(error instanceof Error ? error.message : "خطا"); } }
  async function change(member: Member, nextRole: Exclude<Role, "owner">) { try { await changeMemberRole(business.id, member.user_id, { role: nextRole }); toast.success("نقش عضو تغییر کرد"); void load(); } catch (error) { toast.error(error instanceof Error ? error.message : "خطا"); } }
  async function remove(id: number) { if (!confirm("عضو حذف شود؟")) return; try { await removeMember(business.id, id); toast.success("عضو حذف شد"); if (id === user?.id) router.replace("/select-business"); else void load(); } catch (error) { toast.error(error instanceof Error ? error.message : "خطا"); } }
  async function cancel(id: number) { try { await cancelInvite(business.id, id); toast.success("دعوت لغو شد"); void load(); } catch (error) { toast.error(error instanceof Error ? error.message : "خطا"); } }
  return <section><div className="flex items-center justify-between"><div><p className="text-sm text-brand-muted">دسترسی تیم</p><h1 className="text-2xl font-bold">اعضا</h1></div>{role !== "owner" && <button onClick={() => remove(user!.id)} className="cursor-pointer rounded-lg border border-red-300 px-3 py-2 text-sm text-red-600">خروج از کسب‌وکار</button>}</div><div className="mt-6 overflow-x-auto rounded-2xl border border-brand-border bg-brand-surface"><table className="w-full min-w-[42rem] text-right text-sm"><thead className="text-brand-muted"><tr><th className="p-4">نام</th><th className="p-4">موبایل</th><th className="p-4">نقش</th><th className="p-4">تاریخ عضویت</th><th /></tr></thead><tbody>{members.map(member => <tr key={member.user_id} className="border-t border-brand-border"><td className="p-4">{member.first_name} {member.last_name}</td><td dir="ltr" className="p-4">{member.phone_number}</td><td className="p-4">{canManage(role) && member.role !== "owner" && member.user_id !== user?.id ? <Select value={{ value: member.role, label: roleLabels[member.role] }} onChange={value => change(member, (value?.value ?? member.role) as Exclude<Role, "owner">)} options={roleOptions} /> : roleLabels[member.role]}</td><td className="p-4 text-brand-muted">{new Date(member.created_at).toLocaleDateString("fa-IR")}</td><td className="p-4">{canManage(role) && member.role !== "owner" && <button onClick={() => remove(member.user_id)} className="cursor-pointer text-red-600">حذف</button>}</td></tr>)}</tbody></table></div>{canManage(role) && <><form onSubmit={invite} className="mt-5 flex flex-wrap gap-2 rounded-2xl border border-brand-border bg-brand-surface p-5"><input required value={phone} onChange={event => setPhone(event.target.value)} placeholder="شماره موبایل" dir="ltr" className={`min-w-48 flex-1 ${input}`} /><Select value={{ value: inviteRole, label: roleLabels[inviteRole] }} onChange={value => setInviteRole((value?.value ?? inviteRole) as Exclude<Role, "owner">)} options={roleOptions} /><button className="cursor-pointer rounded-lg bg-brand-accent px-4 font-bold text-white">دعوت عضو</button></form><section className="mt-5 rounded-2xl border border-brand-border bg-brand-surface p-5"><h2 className="font-bold">دعوت‌های در انتظار</h2><div className="mt-3 space-y-2">{invites.length ? invites.map(invite => <div key={invite.id} className="flex items-center justify-between rounded-lg border border-brand-border p-3 text-sm"><span>{invite.first_name} {invite.last_name} <small dir="ltr" className="mr-2 text-brand-muted">{invite.phone_number}</small> · {roleLabels[invite.role]}</span><button onClick={() => cancel(invite.id)} className="cursor-pointer text-red-600">لغو دعوت</button></div>) : <p className="text-sm text-brand-muted">دعوت فعالی وجود ندارد</p>}</div></section></>}</section>;
}
